### ISSUE TITLE
Request for updating of translated content

### ISSUE THREAD

**Issue by huseyinunsal78** [ozwillo/ozwillo-kernel#10]
Translated content (see the screenshot for the English content to be replaced)
1) Hedef Kitle
2) Mod
3) Coğrafi Yer

![screenshot](https://cloud.githubusercontent.com/assets/9558058/13072968/cab59142-d4a4-11e5-90db-4ace7c65b236.png)

**Comment by tbroyer** [comment]
This is a portal issue, not a kernel one.
/cc @bobeal 

Please report issues to https://github.com/ozwillo/ozwillo-issues so we can triage appropriately.

(thanks for the report though)
