### ISSUE TITLE
Update links to terms of use page on Ozwillo's website

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-kernel#18]

**Comment by tbroyer** [comment]
Copied from #19 

Are you telling me there's no "terms of use" page anymore in the website‽ We're asking users to read and accept the Terms of Use when they create an account, so I don't think this can link to a webpage simply saying who is operating the platform, and with a paragraph-long notice on privacy (which is different from terms of use btw).

Who can terminate a user's account? Under which conditions?

**Comment by tbroyer** [comment]
Per https://github.com/ozwillo/ozwillo-site/issues/24 and https://github.com/ozwillo/ozwillo-site/commit/4113266479e5bcbd4c15385f5c1b29cf3c187a75, the “terms of use” page has been reintroduced; only the Bulgarian page's URL changed.

**Comment by tbroyer** [comment]
Fixed by https://github.com/ozwillo/ozwillo-kernel/commit/020ee2f4d11b4be541a368e0963d7b7d227ee373
