### ISSUE TITLE
Wrong link on "Manage my applications" and "Settings" actions in users notifications

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-kernel#22]
The "Manage my applications" and "Settings" actions point to "/my/appsmanagement", which is the old location for the apps page. It is now "/my/apps".

**Comment by tbroyer** [comment]
All Portal URLs actually come from configuration, with no default value at all:
https://github.com/ozwillo/ozwillo-kernel/blob/a0472472ac246cc172b098b1d69a2ce6635da608/oasis-webapp/src/main/java/oasis/urls/UrlsModule.java#L37-L44
https://github.com/ozwillo/ozwillo-kernel/blob/a0472472ac246cc172b098b1d69a2ce6635da608/oasis-webapp/src/main/resources/reference.conf#L40
