### ISSUE TITLE
Encoding problem in emails subjects

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-kernel#25]
Some emails (at least those received when being invited to an organization) have encoding problems :

> =?ANSI_X3.4-1968?Q?Franck_B_vous_invite_=3F_rejo?= =?ANSI_X3.4-1968?Q?indre_l'organisation_SICTIAM_TEST?=

Any idea of the origin and the way to solve it ?

**Comment by tbroyer** [comment]
For some reason, on one of the servers, the default locale was changed to POSIX (rather than something.UTF-8), and that seems to be the reason for that behavior.
